sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t harshagr64/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harshagr64/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-988830324420"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECERET_KEY
