sudo: required
language: generic
services:
	- docker

before_install:
	- docker build -t harshagr64/docker-react -f Dockerfile.dev .

script:
	- docker run harshagr64/docker-react npm run test -- --coverage
