FROM node:alpine

WORKDIR /app

COPY package.json /app

# To Fix Permissions for Packages

RUN npm install

RUN npm config set unsafe-perm true

COPY . /app

RUN chown -R node /app/node_modules

USER node

CMD ["npm", "run", "start"]
